### ISSUE TITLE
Java 8 (1.8.0_05-b13) with Typesafe Activator 1.1.3 fails to run

### ISSUE THREAD

**Issue by dcode** [DrewEaster/realtime-search#4]
I'm somewhat new to Typesafe Activator and Play, but I tried to run your code from a fresh clone and it fails with the following error under 'activator' (1.1.3) and play (2.2.2). Other projects I've tried do not have this issue.

```
[dcode@localhost realtime-search]$ activator play
error: error while loading CharSequence, class file '/usr/java/jdk1.8.0_05/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(bad constant pool tag 15 at byte 1501)
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
[dcode@localhost realtime-search]$ ~/src/play-2.2.2/play
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
java.lang.NoSuchMethodError: scala.Predef$.augmentString(Ljava/lang/String;)Lscala/collection/immutable/StringOps;
    at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:129)
    at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
    at sbt.StandardMain$.<init>(Main.scala:52)
    at sbt.StandardMain$.<clinit>(Main.scala)
    at sbt.xMain.run(Main.scala:26)
    at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:57)
    at xsbt.boot.Launch$.withContextLoader(Launch.scala:77)
    at xsbt.boot.Launch$.run(Launch.scala:57)
    at xsbt.boot.Launch$$anonfun$explicit$1.apply(Launch.scala:45)
    at xsbt.boot.Launch$.launch(Launch.scala:65)
    at xsbt.boot.Launch$.apply(Launch.scala:16)
    at xsbt.boot.Boot$.runImpl(Boot.scala:32)
    at xsbt.boot.Boot$.main(Boot.scala:21)
    at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.NoSuchMethodError: scala.Predef$.augmentString(Ljava/lang/String;)Lscala/collection/immutable/StringOps;
[dcode@localhost realtime-search]$ git show
commit 2b4e832c6acdc824c9f4866077c0070562b46340
Merge: 4959442 d4fdc95
Author: DrewEaster <andrew.easter@gmail.com>
Date:   Thu Jan 30 23:26:42 2014 -0800

    Merge pull request #3 from markusjura/master

    Change tag to playframework

```

**Comment by langley** [comment]
I'm looking at upgrading this to the latest version of Play which is currently 2.4.3. 
See my fork for current status... https://github.com/langley/realtime-search

Oh, and the work is going on in the WIP branch (Work In Progress)
